#!/usr/bin/env python

# -*- coding: utf-8 -*-
import re
import os, sys

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), "closure-linter"))
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), "gflags"))

from closure_linter.gjslint import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
